=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  module ApiDocumentElementLocation
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'BoundingBoxLocation',
          :'CharacterIndexLocation',
          :'DurationLocation',
          :'SpreadsheetLocation'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'location_type'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'bounding_box' => :'BoundingBoxLocation',
          :'character_index' => :'CharacterIndexLocation',
          :'duration' => :'DurationLocation',
          :'spreadsheet' => :'SpreadsheetLocation'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        RagieRubySdk.const_get(klass).build_from_hash(data)
      end
    end
  end

end
