=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class Connection < ApiModelBase
    attr_accessor :id

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :metadata

    attr_accessor :type

    attr_accessor :name

    attr_accessor :source

    attr_accessor :enabled

    attr_accessor :disabled_by_system_reason

    attr_accessor :last_synced_at

    attr_accessor :syncing

    attr_accessor :partition

    attr_accessor :page_limit

    attr_accessor :disabled_by_system

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'metadata' => :'metadata',
        :'type' => :'type',
        :'name' => :'name',
        :'source' => :'source',
        :'enabled' => :'enabled',
        :'disabled_by_system_reason' => :'disabled_by_system_reason',
        :'last_synced_at' => :'last_synced_at',
        :'syncing' => :'syncing',
        :'partition' => :'partition',
        :'page_limit' => :'page_limit',
        :'disabled_by_system' => :'disabled_by_system'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'metadata' => :'Hash<String, MetadataValue>',
        :'type' => :'String',
        :'name' => :'String',
        :'source' => :'Source',
        :'enabled' => :'Boolean',
        :'disabled_by_system_reason' => :'String',
        :'last_synced_at' => :'Time',
        :'syncing' => :'Boolean',
        :'partition' => :'String',
        :'page_limit' => :'Integer',
        :'disabled_by_system' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'source',
        :'disabled_by_system_reason',
        :'last_synced_at',
        :'syncing',
        :'partition',
        :'page_limit',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::Connection` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::Connection`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      else
        self.metadata = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = nil
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      else
        self.enabled = nil
      end

      if attributes.key?(:'disabled_by_system_reason')
        self.disabled_by_system_reason = attributes[:'disabled_by_system_reason']
      else
        self.disabled_by_system_reason = nil
      end

      if attributes.key?(:'last_synced_at')
        self.last_synced_at = attributes[:'last_synced_at']
      end

      if attributes.key?(:'syncing')
        self.syncing = attributes[:'syncing']
      end

      if attributes.key?(:'partition')
        self.partition = attributes[:'partition']
      end

      if attributes.key?(:'page_limit')
        self.page_limit = attributes[:'page_limit']
      else
        self.page_limit = nil
      end

      if attributes.key?(:'disabled_by_system')
        self.disabled_by_system = attributes[:'disabled_by_system']
      else
        self.disabled_by_system = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @enabled.nil?
        invalid_properties.push('invalid value for "enabled", enabled cannot be nil.')
      end

      if @disabled_by_system.nil?
        invalid_properties.push('invalid value for "disabled_by_system", disabled_by_system cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @metadata.nil?
      return false if @type.nil?
      return false if @name.nil?
      return false if @enabled.nil?
      disabled_by_system_reason_validator = EnumAttributeValidator.new('String', ["connection_over_total_page_limit", "authentication_failed"])
      return false unless disabled_by_system_reason_validator.valid?(@disabled_by_system_reason)
      return false if @disabled_by_system.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] enabled Value to be assigned
    def enabled=(enabled)
      if enabled.nil?
        fail ArgumentError, 'enabled cannot be nil'
      end

      @enabled = enabled
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] disabled_by_system_reason Object to be assigned
    def disabled_by_system_reason=(disabled_by_system_reason)
      validator = EnumAttributeValidator.new('String', ["connection_over_total_page_limit", "authentication_failed"])
      unless validator.valid?(disabled_by_system_reason)
        fail ArgumentError, "invalid value for \"disabled_by_system_reason\", must be one of #{validator.allowable_values}."
      end
      @disabled_by_system_reason = disabled_by_system_reason
    end

    # Custom attribute writer method with validation
    # @param [Object] disabled_by_system Value to be assigned
    def disabled_by_system=(disabled_by_system)
      if disabled_by_system.nil?
        fail ArgumentError, 'disabled_by_system cannot be nil'
      end

      @disabled_by_system = disabled_by_system
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          metadata == o.metadata &&
          type == o.type &&
          name == o.name &&
          source == o.source &&
          enabled == o.enabled &&
          disabled_by_system_reason == o.disabled_by_system_reason &&
          last_synced_at == o.last_synced_at &&
          syncing == o.syncing &&
          partition == o.partition &&
          page_limit == o.page_limit &&
          disabled_by_system == o.disabled_by_system
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created_at, updated_at, metadata, type, name, source, enabled, disabled_by_system_reason, last_synced_at, syncing, partition, page_limit, disabled_by_system].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
