=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  module Connection2
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'PublicBackblazeConnection',
          :'PublicFreshdeskConnection',
          :'PublicGCSConnection',
          :'PublicIntercomConnection',
          :'PublicS3CompatibleConnection',
          :'PublicZendeskConnection'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'provider'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'backblaze' => :'PublicBackblazeConnection',
          :'freshdesk' => :'PublicFreshdeskConnection',
          :'gcs' => :'PublicGCSConnection',
          :'intercom' => :'PublicIntercomConnection',
          :'s3' => :'PublicS3CompatibleConnection',
          :'zendesk' => :'PublicZendeskConnection'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        RagieRubySdk.const_get(klass).build_from_hash(data)
      end
    end
  end

end
