=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class EntityExtractedWebhookPayload < ApiModelBase
    attr_accessor :entity_id

    attr_accessor :document_id

    attr_accessor :instruction_id

    attr_accessor :document_metadata

    attr_accessor :document_external_id

    attr_accessor :document_name

    attr_accessor :partition

    attr_accessor :sync_id

    attr_accessor :data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'entity_id' => :'entity_id',
        :'document_id' => :'document_id',
        :'instruction_id' => :'instruction_id',
        :'document_metadata' => :'document_metadata',
        :'document_external_id' => :'document_external_id',
        :'document_name' => :'document_name',
        :'partition' => :'partition',
        :'sync_id' => :'sync_id',
        :'data' => :'data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'entity_id' => :'String',
        :'document_id' => :'String',
        :'instruction_id' => :'String',
        :'document_metadata' => :'Hash<String, Object>',
        :'document_external_id' => :'String',
        :'document_name' => :'String',
        :'partition' => :'String',
        :'sync_id' => :'String',
        :'data' => :'Hash<String, Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'document_external_id',
        :'sync_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::EntityExtractedWebhookPayload` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::EntityExtractedWebhookPayload`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'entity_id')
        self.entity_id = attributes[:'entity_id']
      else
        self.entity_id = nil
      end

      if attributes.key?(:'document_id')
        self.document_id = attributes[:'document_id']
      else
        self.document_id = nil
      end

      if attributes.key?(:'instruction_id')
        self.instruction_id = attributes[:'instruction_id']
      else
        self.instruction_id = nil
      end

      if attributes.key?(:'document_metadata')
        if (value = attributes[:'document_metadata']).is_a?(Hash)
          self.document_metadata = value
        end
      else
        self.document_metadata = nil
      end

      if attributes.key?(:'document_external_id')
        self.document_external_id = attributes[:'document_external_id']
      else
        self.document_external_id = nil
      end

      if attributes.key?(:'document_name')
        self.document_name = attributes[:'document_name']
      else
        self.document_name = nil
      end

      if attributes.key?(:'partition')
        self.partition = attributes[:'partition']
      else
        self.partition = nil
      end

      if attributes.key?(:'sync_id')
        self.sync_id = attributes[:'sync_id']
      else
        self.sync_id = nil
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      else
        self.data = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @entity_id.nil?
        invalid_properties.push('invalid value for "entity_id", entity_id cannot be nil.')
      end

      if @document_id.nil?
        invalid_properties.push('invalid value for "document_id", document_id cannot be nil.')
      end

      if @instruction_id.nil?
        invalid_properties.push('invalid value for "instruction_id", instruction_id cannot be nil.')
      end

      if @document_metadata.nil?
        invalid_properties.push('invalid value for "document_metadata", document_metadata cannot be nil.')
      end

      if @document_name.nil?
        invalid_properties.push('invalid value for "document_name", document_name cannot be nil.')
      end

      if @partition.nil?
        invalid_properties.push('invalid value for "partition", partition cannot be nil.')
      end

      if @data.nil?
        invalid_properties.push('invalid value for "data", data cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @entity_id.nil?
      return false if @document_id.nil?
      return false if @instruction_id.nil?
      return false if @document_metadata.nil?
      return false if @document_name.nil?
      return false if @partition.nil?
      return false if @data.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] entity_id Value to be assigned
    def entity_id=(entity_id)
      if entity_id.nil?
        fail ArgumentError, 'entity_id cannot be nil'
      end

      @entity_id = entity_id
    end

    # Custom attribute writer method with validation
    # @param [Object] document_id Value to be assigned
    def document_id=(document_id)
      if document_id.nil?
        fail ArgumentError, 'document_id cannot be nil'
      end

      @document_id = document_id
    end

    # Custom attribute writer method with validation
    # @param [Object] instruction_id Value to be assigned
    def instruction_id=(instruction_id)
      if instruction_id.nil?
        fail ArgumentError, 'instruction_id cannot be nil'
      end

      @instruction_id = instruction_id
    end

    # Custom attribute writer method with validation
    # @param [Object] document_metadata Value to be assigned
    def document_metadata=(document_metadata)
      if document_metadata.nil?
        fail ArgumentError, 'document_metadata cannot be nil'
      end

      @document_metadata = document_metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] document_name Value to be assigned
    def document_name=(document_name)
      if document_name.nil?
        fail ArgumentError, 'document_name cannot be nil'
      end

      @document_name = document_name
    end

    # Custom attribute writer method with validation
    # @param [Object] partition Value to be assigned
    def partition=(partition)
      if partition.nil?
        fail ArgumentError, 'partition cannot be nil'
      end

      @partition = partition
    end

    # Custom attribute writer method with validation
    # @param [Object] data Value to be assigned
    def data=(data)
      if data.nil?
        fail ArgumentError, 'data cannot be nil'
      end

      @data = data
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          entity_id == o.entity_id &&
          document_id == o.document_id &&
          instruction_id == o.instruction_id &&
          document_metadata == o.document_metadata &&
          document_external_id == o.document_external_id &&
          document_name == o.document_name &&
          partition == o.partition &&
          sync_id == o.sync_id &&
          data == o.data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [entity_id, document_id, instruction_id, document_metadata, document_external_id, document_name, partition, sync_id, data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
