=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class IntercomData < ApiModelBase
    attr_accessor :articles_help_center

    attr_accessor :admins

    attr_accessor :contacts

    attr_accessor :conversations

    attr_accessor :conversation_attachments

    attr_accessor :conversation_notes

    attr_accessor :tickets

    attr_accessor :ticket_attachments

    attr_accessor :ticket_comments

    attr_accessor :ticket_notes

    attr_accessor :filter_user_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'articles_help_center' => :'articles_help_center',
        :'admins' => :'admins',
        :'contacts' => :'contacts',
        :'conversations' => :'conversations',
        :'conversation_attachments' => :'conversation_attachments',
        :'conversation_notes' => :'conversation_notes',
        :'tickets' => :'tickets',
        :'ticket_attachments' => :'ticket_attachments',
        :'ticket_comments' => :'ticket_comments',
        :'ticket_notes' => :'ticket_notes',
        :'filter_user_id' => :'filter_user_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'articles_help_center' => :'Boolean',
        :'admins' => :'Boolean',
        :'contacts' => :'Boolean',
        :'conversations' => :'Boolean',
        :'conversation_attachments' => :'Boolean',
        :'conversation_notes' => :'Boolean',
        :'tickets' => :'Boolean',
        :'ticket_attachments' => :'Boolean',
        :'ticket_comments' => :'Boolean',
        :'ticket_notes' => :'Boolean',
        :'filter_user_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'filter_user_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::IntercomData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::IntercomData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'articles_help_center')
        self.articles_help_center = attributes[:'articles_help_center']
      else
        self.articles_help_center = false
      end

      if attributes.key?(:'admins')
        self.admins = attributes[:'admins']
      else
        self.admins = false
      end

      if attributes.key?(:'contacts')
        self.contacts = attributes[:'contacts']
      else
        self.contacts = false
      end

      if attributes.key?(:'conversations')
        self.conversations = attributes[:'conversations']
      else
        self.conversations = false
      end

      if attributes.key?(:'conversation_attachments')
        self.conversation_attachments = attributes[:'conversation_attachments']
      else
        self.conversation_attachments = false
      end

      if attributes.key?(:'conversation_notes')
        self.conversation_notes = attributes[:'conversation_notes']
      else
        self.conversation_notes = false
      end

      if attributes.key?(:'tickets')
        self.tickets = attributes[:'tickets']
      else
        self.tickets = false
      end

      if attributes.key?(:'ticket_attachments')
        self.ticket_attachments = attributes[:'ticket_attachments']
      else
        self.ticket_attachments = false
      end

      if attributes.key?(:'ticket_comments')
        self.ticket_comments = attributes[:'ticket_comments']
      else
        self.ticket_comments = false
      end

      if attributes.key?(:'ticket_notes')
        self.ticket_notes = attributes[:'ticket_notes']
      else
        self.ticket_notes = false
      end

      if attributes.key?(:'filter_user_id')
        self.filter_user_id = attributes[:'filter_user_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          articles_help_center == o.articles_help_center &&
          admins == o.admins &&
          contacts == o.contacts &&
          conversations == o.conversations &&
          conversation_attachments == o.conversation_attachments &&
          conversation_notes == o.conversation_notes &&
          tickets == o.tickets &&
          ticket_attachments == o.ticket_attachments &&
          ticket_comments == o.ticket_comments &&
          ticket_notes == o.ticket_notes &&
          filter_user_id == o.filter_user_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [articles_help_center, admins, contacts, conversations, conversation_attachments, conversation_notes, tickets, ticket_attachments, ticket_comments, ticket_notes, filter_user_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
