=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class IntercomData
    attr_accessor :admins

    attr_accessor :tickets

    attr_accessor :contacts

    attr_accessor :ticket_attachments

    attr_accessor :ticket_comments

    attr_accessor :ticket_notes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'admins' => :'admins',
        :'tickets' => :'tickets',
        :'contacts' => :'contacts',
        :'ticket_attachments' => :'ticket_attachments',
        :'ticket_comments' => :'ticket_comments',
        :'ticket_notes' => :'ticket_notes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'admins' => :'Boolean',
        :'tickets' => :'Boolean',
        :'contacts' => :'Boolean',
        :'ticket_attachments' => :'Boolean',
        :'ticket_comments' => :'Boolean',
        :'ticket_notes' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::IntercomData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::IntercomData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'admins')
        self.admins = attributes[:'admins']
      else
        self.admins = nil
      end

      if attributes.key?(:'tickets')
        self.tickets = attributes[:'tickets']
      else
        self.tickets = nil
      end

      if attributes.key?(:'contacts')
        self.contacts = attributes[:'contacts']
      else
        self.contacts = nil
      end

      if attributes.key?(:'ticket_attachments')
        self.ticket_attachments = attributes[:'ticket_attachments']
      else
        self.ticket_attachments = nil
      end

      if attributes.key?(:'ticket_comments')
        self.ticket_comments = attributes[:'ticket_comments']
      else
        self.ticket_comments = nil
      end

      if attributes.key?(:'ticket_notes')
        self.ticket_notes = attributes[:'ticket_notes']
      else
        self.ticket_notes = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @admins.nil?
        invalid_properties.push('invalid value for "admins", admins cannot be nil.')
      end

      if @tickets.nil?
        invalid_properties.push('invalid value for "tickets", tickets cannot be nil.')
      end

      if @contacts.nil?
        invalid_properties.push('invalid value for "contacts", contacts cannot be nil.')
      end

      if @ticket_attachments.nil?
        invalid_properties.push('invalid value for "ticket_attachments", ticket_attachments cannot be nil.')
      end

      if @ticket_comments.nil?
        invalid_properties.push('invalid value for "ticket_comments", ticket_comments cannot be nil.')
      end

      if @ticket_notes.nil?
        invalid_properties.push('invalid value for "ticket_notes", ticket_notes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @admins.nil?
      return false if @tickets.nil?
      return false if @contacts.nil?
      return false if @ticket_attachments.nil?
      return false if @ticket_comments.nil?
      return false if @ticket_notes.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] admins Value to be assigned
    def admins=(admins)
      if admins.nil?
        fail ArgumentError, 'admins cannot be nil'
      end

      @admins = admins
    end

    # Custom attribute writer method with validation
    # @param [Object] tickets Value to be assigned
    def tickets=(tickets)
      if tickets.nil?
        fail ArgumentError, 'tickets cannot be nil'
      end

      @tickets = tickets
    end

    # Custom attribute writer method with validation
    # @param [Object] contacts Value to be assigned
    def contacts=(contacts)
      if contacts.nil?
        fail ArgumentError, 'contacts cannot be nil'
      end

      @contacts = contacts
    end

    # Custom attribute writer method with validation
    # @param [Object] ticket_attachments Value to be assigned
    def ticket_attachments=(ticket_attachments)
      if ticket_attachments.nil?
        fail ArgumentError, 'ticket_attachments cannot be nil'
      end

      @ticket_attachments = ticket_attachments
    end

    # Custom attribute writer method with validation
    # @param [Object] ticket_comments Value to be assigned
    def ticket_comments=(ticket_comments)
      if ticket_comments.nil?
        fail ArgumentError, 'ticket_comments cannot be nil'
      end

      @ticket_comments = ticket_comments
    end

    # Custom attribute writer method with validation
    # @param [Object] ticket_notes Value to be assigned
    def ticket_notes=(ticket_notes)
      if ticket_notes.nil?
        fail ArgumentError, 'ticket_notes cannot be nil'
      end

      @ticket_notes = ticket_notes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          admins == o.admins &&
          tickets == o.tickets &&
          contacts == o.contacts &&
          ticket_attachments == o.ticket_attachments &&
          ticket_comments == o.ticket_comments &&
          ticket_notes == o.ticket_notes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [admins, tickets, contacts, ticket_attachments, ticket_comments, ticket_notes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = RagieRubySdk.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
