=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class OAuthUrlCreate < ApiModelBase
    attr_accessor :redirect_uri

    attr_accessor :partition

    # The type of connector you want to create, such as google_drive, notion, hubspot, etc.
    attr_accessor :source_type

    # Metadata for the document. Keys must be strings. Values may be strings, numbers, booleans, or lists of strings. Numbers may be integers or floating point and will be converted to 64 bit floating point. 1000 total values are allowed. Each item in an array counts towards the total. The following keys are reserved for internal use: `document_id`, `document_type`, `document_source`, `document_name`, `document_uploaded_at`, `start_time`, `end_time`, `chunk_content_type`.
    attr_accessor :metadata

    attr_accessor :mode

    attr_accessor :theme

    attr_accessor :page_limit

    # Optional config per connector
    attr_accessor :config

    attr_accessor :authenticator_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'redirect_uri' => :'redirect_uri',
        :'partition' => :'partition',
        :'source_type' => :'source_type',
        :'metadata' => :'metadata',
        :'mode' => :'mode',
        :'theme' => :'theme',
        :'page_limit' => :'page_limit',
        :'config' => :'config',
        :'authenticator_id' => :'authenticator_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'redirect_uri' => :'String',
        :'partition' => :'String',
        :'source_type' => :'ConnectorSource',
        :'metadata' => :'Hash<String, MetadataValue>',
        :'mode' => :'Mode1',
        :'theme' => :'String',
        :'page_limit' => :'Integer',
        :'config' => :'Hash<String, Object>',
        :'authenticator_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'partition',
        :'mode',
        :'theme',
        :'page_limit',
        :'authenticator_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::OAuthUrlCreate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::OAuthUrlCreate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'redirect_uri')
        self.redirect_uri = attributes[:'redirect_uri']
      else
        self.redirect_uri = nil
      end

      if attributes.key?(:'partition')
        self.partition = attributes[:'partition']
      end

      if attributes.key?(:'source_type')
        self.source_type = attributes[:'source_type']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end

      if attributes.key?(:'theme')
        self.theme = attributes[:'theme']
      end

      if attributes.key?(:'page_limit')
        self.page_limit = attributes[:'page_limit']
      end

      if attributes.key?(:'config')
        if (value = attributes[:'config']).is_a?(Hash)
          self.config = value
        end
      end

      if attributes.key?(:'authenticator_id')
        self.authenticator_id = attributes[:'authenticator_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @redirect_uri.nil?
        invalid_properties.push('invalid value for "redirect_uri", redirect_uri cannot be nil.')
      end

      if !@page_limit.nil? && @page_limit < 1
        invalid_properties.push('invalid value for "page_limit", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @redirect_uri.nil?
      theme_validator = EnumAttributeValidator.new('String', ["light", "dark", "system"])
      return false unless theme_validator.valid?(@theme)
      return false if !@page_limit.nil? && @page_limit < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] redirect_uri Value to be assigned
    def redirect_uri=(redirect_uri)
      if redirect_uri.nil?
        fail ArgumentError, 'redirect_uri cannot be nil'
      end

      @redirect_uri = redirect_uri
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] theme Object to be assigned
    def theme=(theme)
      validator = EnumAttributeValidator.new('String', ["light", "dark", "system"])
      unless validator.valid?(theme)
        fail ArgumentError, "invalid value for \"theme\", must be one of #{validator.allowable_values}."
      end
      @theme = theme
    end

    # Custom attribute writer method with validation
    # @param [Object] page_limit Value to be assigned
    def page_limit=(page_limit)
      if !page_limit.nil? && page_limit < 1
        fail ArgumentError, 'invalid value for "page_limit", must be greater than or equal to 1.'
      end

      @page_limit = page_limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          redirect_uri == o.redirect_uri &&
          partition == o.partition &&
          source_type == o.source_type &&
          metadata == o.metadata &&
          mode == o.mode &&
          theme == o.theme &&
          page_limit == o.page_limit &&
          config == o.config &&
          authenticator_id == o.authenticator_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [redirect_uri, partition, source_type, metadata, mode, theme, page_limit, config, authenticator_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
