=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class PartitionDetail < ApiModelBase
    attr_accessor :name

    attr_accessor :is_default

    attr_accessor :limit_exceeded_at

    attr_accessor :description

    attr_accessor :context_aware

    attr_accessor :metadata_schema

    attr_accessor :limits

    attr_accessor :stats

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'is_default' => :'is_default',
        :'limit_exceeded_at' => :'limit_exceeded_at',
        :'description' => :'description',
        :'context_aware' => :'context_aware',
        :'metadata_schema' => :'metadata_schema',
        :'limits' => :'limits',
        :'stats' => :'stats'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'is_default' => :'Boolean',
        :'limit_exceeded_at' => :'Time',
        :'description' => :'String',
        :'context_aware' => :'Boolean',
        :'metadata_schema' => :'Hash<String, CreatePartitionParamsMetadataSchemaValue>',
        :'limits' => :'PartitionLimits',
        :'stats' => :'PartitionStats'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'limit_exceeded_at',
        :'description',
        :'metadata_schema',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::PartitionDetail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::PartitionDetail`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'is_default')
        self.is_default = attributes[:'is_default']
      else
        self.is_default = nil
      end

      if attributes.key?(:'limit_exceeded_at')
        self.limit_exceeded_at = attributes[:'limit_exceeded_at']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'context_aware')
        self.context_aware = attributes[:'context_aware']
      else
        self.context_aware = nil
      end

      if attributes.key?(:'metadata_schema')
        if (value = attributes[:'metadata_schema']).is_a?(Hash)
          self.metadata_schema = value
        end
      else
        self.metadata_schema = nil
      end

      if attributes.key?(:'limits')
        self.limits = attributes[:'limits']
      else
        self.limits = nil
      end

      if attributes.key?(:'stats')
        self.stats = attributes[:'stats']
      else
        self.stats = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @is_default.nil?
        invalid_properties.push('invalid value for "is_default", is_default cannot be nil.')
      end

      if @context_aware.nil?
        invalid_properties.push('invalid value for "context_aware", context_aware cannot be nil.')
      end

      if @limits.nil?
        invalid_properties.push('invalid value for "limits", limits cannot be nil.')
      end

      if @stats.nil?
        invalid_properties.push('invalid value for "stats", stats cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @is_default.nil?
      return false if @context_aware.nil?
      return false if @limits.nil?
      return false if @stats.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] is_default Value to be assigned
    def is_default=(is_default)
      if is_default.nil?
        fail ArgumentError, 'is_default cannot be nil'
      end

      @is_default = is_default
    end

    # Custom attribute writer method with validation
    # @param [Object] context_aware Value to be assigned
    def context_aware=(context_aware)
      if context_aware.nil?
        fail ArgumentError, 'context_aware cannot be nil'
      end

      @context_aware = context_aware
    end

    # Custom attribute writer method with validation
    # @param [Object] limits Value to be assigned
    def limits=(limits)
      if limits.nil?
        fail ArgumentError, 'limits cannot be nil'
      end

      @limits = limits
    end

    # Custom attribute writer method with validation
    # @param [Object] stats Value to be assigned
    def stats=(stats)
      if stats.nil?
        fail ArgumentError, 'stats cannot be nil'
      end

      @stats = stats
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          is_default == o.is_default &&
          limit_exceeded_at == o.limit_exceeded_at &&
          description == o.description &&
          context_aware == o.context_aware &&
          metadata_schema == o.metadata_schema &&
          limits == o.limits &&
          stats == o.stats
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, is_default, limit_exceeded_at, description, context_aware, metadata_schema, limits, stats].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
