=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class RagieApiSchemaResponseUsage < ApiModelBase
    attr_accessor :input_tokens

    attr_accessor :input_token_details

    attr_accessor :output_tokens

    attr_accessor :output_token_details

    attr_accessor :total_tokens

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'input_tokens' => :'input_tokens',
        :'input_token_details' => :'input_token_details',
        :'output_tokens' => :'output_tokens',
        :'output_token_details' => :'output_token_details',
        :'total_tokens' => :'total_tokens'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'input_tokens' => :'Integer',
        :'input_token_details' => :'InputTokenDetails',
        :'output_tokens' => :'Integer',
        :'output_token_details' => :'OutputTokenDetails',
        :'total_tokens' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::RagieApiSchemaResponseUsage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::RagieApiSchemaResponseUsage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'input_tokens')
        self.input_tokens = attributes[:'input_tokens']
      else
        self.input_tokens = nil
      end

      if attributes.key?(:'input_token_details')
        self.input_token_details = attributes[:'input_token_details']
      end

      if attributes.key?(:'output_tokens')
        self.output_tokens = attributes[:'output_tokens']
      else
        self.output_tokens = nil
      end

      if attributes.key?(:'output_token_details')
        self.output_token_details = attributes[:'output_token_details']
      end

      if attributes.key?(:'total_tokens')
        self.total_tokens = attributes[:'total_tokens']
      else
        self.total_tokens = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @input_tokens.nil?
        invalid_properties.push('invalid value for "input_tokens", input_tokens cannot be nil.')
      end

      if @output_tokens.nil?
        invalid_properties.push('invalid value for "output_tokens", output_tokens cannot be nil.')
      end

      if @total_tokens.nil?
        invalid_properties.push('invalid value for "total_tokens", total_tokens cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @input_tokens.nil?
      return false if @output_tokens.nil?
      return false if @total_tokens.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] input_tokens Value to be assigned
    def input_tokens=(input_tokens)
      if input_tokens.nil?
        fail ArgumentError, 'input_tokens cannot be nil'
      end

      @input_tokens = input_tokens
    end

    # Custom attribute writer method with validation
    # @param [Object] output_tokens Value to be assigned
    def output_tokens=(output_tokens)
      if output_tokens.nil?
        fail ArgumentError, 'output_tokens cannot be nil'
      end

      @output_tokens = output_tokens
    end

    # Custom attribute writer method with validation
    # @param [Object] total_tokens Value to be assigned
    def total_tokens=(total_tokens)
      if total_tokens.nil?
        fail ArgumentError, 'total_tokens cannot be nil'
      end

      @total_tokens = total_tokens
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          input_tokens == o.input_tokens &&
          input_token_details == o.input_token_details &&
          output_tokens == o.output_tokens &&
          output_token_details == o.output_token_details &&
          total_tokens == o.total_tokens
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [input_tokens, input_token_details, output_tokens, output_token_details, total_tokens].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
