=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module RagieRubySdk
  class ScoredChunk < ApiModelBase
    attr_accessor :text

    attr_accessor :score

    attr_accessor :id

    attr_accessor :index

    attr_accessor :metadata

    attr_accessor :document_id

    attr_accessor :document_name

    attr_accessor :document_metadata

    attr_accessor :links

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'text' => :'text',
        :'score' => :'score',
        :'id' => :'id',
        :'index' => :'index',
        :'metadata' => :'metadata',
        :'document_id' => :'document_id',
        :'document_name' => :'document_name',
        :'document_metadata' => :'document_metadata',
        :'links' => :'links'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'text' => :'String',
        :'score' => :'Float',
        :'id' => :'String',
        :'index' => :'Integer',
        :'metadata' => :'Hash<String, Object>',
        :'document_id' => :'String',
        :'document_name' => :'String',
        :'document_metadata' => :'Hash<String, Object>',
        :'links' => :'Hash<String, Link>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RagieRubySdk::ScoredChunk` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RagieRubySdk::ScoredChunk`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      else
        self.text = nil
      end

      if attributes.key?(:'score')
        self.score = attributes[:'score']
      else
        self.score = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'index')
        self.index = attributes[:'index']
      else
        self.index = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'document_id')
        self.document_id = attributes[:'document_id']
      else
        self.document_id = nil
      end

      if attributes.key?(:'document_name')
        self.document_name = attributes[:'document_name']
      else
        self.document_name = nil
      end

      if attributes.key?(:'document_metadata')
        if (value = attributes[:'document_metadata']).is_a?(Hash)
          self.document_metadata = value
        end
      else
        self.document_metadata = nil
      end

      if attributes.key?(:'links')
        if (value = attributes[:'links']).is_a?(Hash)
          self.links = value
        end
      else
        self.links = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @text.nil?
        invalid_properties.push('invalid value for "text", text cannot be nil.')
      end

      if @score.nil?
        invalid_properties.push('invalid value for "score", score cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @index.nil?
        invalid_properties.push('invalid value for "index", index cannot be nil.')
      end

      if @document_id.nil?
        invalid_properties.push('invalid value for "document_id", document_id cannot be nil.')
      end

      if @document_name.nil?
        invalid_properties.push('invalid value for "document_name", document_name cannot be nil.')
      end

      if @document_metadata.nil?
        invalid_properties.push('invalid value for "document_metadata", document_metadata cannot be nil.')
      end

      if @links.nil?
        invalid_properties.push('invalid value for "links", links cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @text.nil?
      return false if @score.nil?
      return false if @id.nil?
      return false if @index.nil?
      return false if @document_id.nil?
      return false if @document_name.nil?
      return false if @document_metadata.nil?
      return false if @links.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if text.nil?
        fail ArgumentError, 'text cannot be nil'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] score Value to be assigned
    def score=(score)
      if score.nil?
        fail ArgumentError, 'score cannot be nil'
      end

      @score = score
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] index Value to be assigned
    def index=(index)
      if index.nil?
        fail ArgumentError, 'index cannot be nil'
      end

      @index = index
    end

    # Custom attribute writer method with validation
    # @param [Object] document_id Value to be assigned
    def document_id=(document_id)
      if document_id.nil?
        fail ArgumentError, 'document_id cannot be nil'
      end

      @document_id = document_id
    end

    # Custom attribute writer method with validation
    # @param [Object] document_name Value to be assigned
    def document_name=(document_name)
      if document_name.nil?
        fail ArgumentError, 'document_name cannot be nil'
      end

      @document_name = document_name
    end

    # Custom attribute writer method with validation
    # @param [Object] document_metadata Value to be assigned
    def document_metadata=(document_metadata)
      if document_metadata.nil?
        fail ArgumentError, 'document_metadata cannot be nil'
      end

      @document_metadata = document_metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] links Value to be assigned
    def links=(links)
      if links.nil?
        fail ArgumentError, 'links cannot be nil'
      end

      @links = links
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          text == o.text &&
          score == o.score &&
          id == o.id &&
          index == o.index &&
          metadata == o.metadata &&
          document_id == o.document_id &&
          document_name == o.document_name &&
          document_metadata == o.document_metadata &&
          links == o.links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [text, score, id, index, metadata, document_id, document_name, document_metadata, links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
