=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::AuthenticatorGoogleDriveConnection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::AuthenticatorGoogleDriveConnection do
  #let(:instance) { RagieRubySdk::AuthenticatorGoogleDriveConnection.new }

  describe 'test an instance of AuthenticatorGoogleDriveConnection' do
    it 'should create an instance of AuthenticatorGoogleDriveConnection' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::AuthenticatorGoogleDriveConnection)
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["google_drive"])
      # validator.allowable_values.each do |value|
      #   expect { instance.provider = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "credentials"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
