=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::CharacterIndexLocation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::CharacterIndexLocation do
  #let(:instance) { RagieRubySdk::CharacterIndexLocation.new }

  describe 'test an instance of CharacterIndexLocation' do
    it 'should create an instance of CharacterIndexLocation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::CharacterIndexLocation)
    end
  end

  describe 'test attribute "location_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["character_index"])
      # validator.allowable_values.each do |value|
      #   expect { instance.location_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "start_char_index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_char_index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
