=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ConnectorSource
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ConnectorSource do
  let(:instance) { OpenapiClient::ConnectorSource.new }

  describe 'test an instance of ConnectorSource' do
    it 'should create an instance of ConnectorSource' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ConnectorSource)
    end
  end

end
