=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::InputTokenDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::InputTokenDetails do
  #let(:instance) { RagieRubySdk::InputTokenDetails.new }

  describe 'test an instance of InputTokenDetails' do
    it 'should create an instance of InputTokenDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::InputTokenDetails)
    end
  end

  describe 'test attribute "cached_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
