=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.16.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::MediaModeParam
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::MediaModeParam do
  let(:instance) { RagieRubySdk::MediaModeParam.new }

  describe 'test an instance of MediaModeParam' do
    it 'should create an instance of MediaModeParam' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::MediaModeParam)
    end
  end

  describe 'test attribute "static"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["hi_res", "fast"])
      # validator.allowable_values.each do |value|
      #   expect { instance.static = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "audio"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "video"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["audio_only", "video_only", "audio_video"])
      # validator.allowable_values.each do |value|
      #   expect { instance.video = value }.not_to raise_error
      # end
    end
  end

end
