=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::OAuthCredentials
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::OAuthCredentials do
  #let(:instance) { RagieRubySdk::OAuthCredentials.new }

  describe 'test an instance of OAuthCredentials' do
    it 'should create an instance of OAuthCredentials' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::OAuthCredentials)
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["atlassian", "dropbox", "microsoft", "salesforce", "slack", "hubspot"])
      # validator.allowable_values.each do |value|
      #   expect { instance.provider = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "client_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "client_secret"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "domain"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
