=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PartitionLimitResetWebhookPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PartitionLimitResetWebhookPayload do
  let(:instance) { OpenapiClient::PartitionLimitResetWebhookPayload.new }

  describe 'test an instance of PartitionLimitResetWebhookPayload' do
    it 'should create an instance of PartitionLimitResetWebhookPayload' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PartitionLimitResetWebhookPayload)
    end
  end

  describe 'test attribute "partition"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
