=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RagieRubySdk::SetConnectionEnabledPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RagieRubySdk::SetConnectionEnabledPayload do
  #let(:instance) { RagieRubySdk::SetConnectionEnabledPayload.new }

  describe 'test an instance of SetConnectionEnabledPayload' do
    it 'should create an instance of SetConnectionEnabledPayload' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RagieRubySdk::SetConnectionEnabledPayload)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["connection_over_total_page_limit", "authentication_failed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reason = value }.not_to raise_error
      # end
    end
  end

end
