=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for RagieRubySdk::AuthenticatorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticatorsApi' do
  before do
    # run before each test
    @api_instance = RagieRubySdk::AuthenticatorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticatorsApi' do
    it 'should create an instance of AuthenticatorsApi' do
      expect(@api_instance).to be_instance_of(RagieRubySdk::AuthenticatorsApi)
    end
  end

  # unit tests for create_authenticator
  # Create Authenticator
  # Create White labeled connector credentials
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [BaseGetAuthenticator]
  describe 'create_authenticator test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_authenticator_connection
  # Create Authenticator Connection
  # Create a connector for a given authenticator. This requires credentials dependent on the provider. For google drive it is a refresh token.
  # @param authenticator_id 
  # @param create_authenticator_connection 
  # @param [Hash] opts the optional parameters
  # @return [Connection]
  describe 'create_authenticator_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_authenticator_connection
  # Delete Authenticator
  # Delete an authenticator. This requires all connections created by that authenticator to be deleted first.
  # @param authenticator_id 
  # @param [Hash] opts the optional parameters
  # @return [ResponseOK]
  describe 'delete_authenticator_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_authenticators
  # List Authenticators
  # List all authenticators sorted by created_at in descending order. Results are paginated with a max limit of 100. When more authenticators are available, a &#x60;cursor&#x60; will be provided. Use the &#x60;cursor&#x60; parameter to retrieve the subsequent page.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An opaque cursor for pagination
  # @option opts [Integer] :page_size The number of items per page (must be greater than 0 and less than or equal to 100)
  # @return [AuthenticatorList]
  describe 'list_authenticators test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
