=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for RagieRubySdk::DocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentsApi' do
  before do
    # run before each test
    @api_instance = RagieRubySdk::DocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentsApi' do
    it 'should create an instance of DocumentsApi' do
      expect(@api_instance).to be_instance_of(RagieRubySdk::DocumentsApi)
    end
  end

  # unit tests for create_document
  # Create Document
  # On ingest, the document goes through a series of steps before it is ready for retrieval. Each step is reflected in the status of the document which can be one of [&#x60;pending&#x60;, &#x60;partitioning&#x60;, &#x60;partitioned&#x60;, &#x60;refined&#x60;, &#x60;chunked&#x60;, &#x60;indexed&#x60;, &#x60;summary_indexed&#x60;, &#x60;keyword_indexed&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;]. The document is available for retrieval once it is in ready state. The summary index step can take a few seconds. You can optionally use the document for retrieval once it is in &#x60;indexed&#x60; state. However the summary will only be available once the state has changed to &#x60;summary_indexed&#x60; or &#x60;ready&#x60;.
  # @param file The binary file to upload, extract, and index for retrieval. The following file types are supported: Plain Text: &#x60;.eml&#x60; &#x60;.html&#x60; &#x60;.json&#x60; &#x60;.md&#x60; &#x60;.msg&#x60; &#x60;.rst&#x60; &#x60;.rtf&#x60; &#x60;.txt&#x60; &#x60;.xml&#x60; Images: &#x60;.png&#x60; &#x60;.webp&#x60; &#x60;.jpg&#x60; &#x60;.jpeg&#x60; &#x60;.tiff&#x60; &#x60;.bmp&#x60; &#x60;.heic&#x60; Documents: &#x60;.csv&#x60; &#x60;.doc&#x60; &#x60;.docx&#x60; &#x60;.epub&#x60; &#x60;.epub+zip&#x60; &#x60;.odt&#x60; &#x60;.pdf&#x60; &#x60;.ppt&#x60; &#x60;.pptx&#x60; &#x60;.tsv&#x60; &#x60;.xlsx&#x60; &#x60;.xls&#x60;. PDF files over 2000 pages are not supported in hi_res mode.
  # @param [Hash] opts the optional parameters
  # @option opts [Mode2] :mode 
  # @option opts [Hash<String, MetadataValue1>] :metadata Metadata for the document. Keys must be strings. Values may be strings, numbers, booleans, or lists of strings. Numbers may be integers or floating point and will be converted to 64 bit floating point. 1000 total values are allowed. Each item in an array counts towards the total. The following keys are reserved for internal use: &#x60;document_id&#x60;, &#x60;document_type&#x60;, &#x60;document_source&#x60;, &#x60;document_name&#x60;, &#x60;document_uploaded_at&#x60;, &#x60;start_time&#x60;, &#x60;end_time&#x60;.
  # @option opts [String] :external_id An optional identifier for the document. A common value might be an id in an external system or the URL where the source file may be found.
  # @option opts [String] :name An optional name for the document. If set, the document will have this name. Otherwise it will default to the file&#39;s name.
  # @option opts [String] :partition An optional partition identifier. Documents can be scoped to a partition. Partitions must be lowercase alphanumeric and may only include the special characters &#x60;_&#x60; and &#x60;-&#x60;.  A partition is created any time a document is created.
  # @return [Document]
  describe 'create_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_document_from_url
  # Create Document From Url
  # Ingest a document from a publicly accessible URL. On ingest, the document goes through a series of steps before it is ready for retrieval. Each step is reflected in the status of the document which can be one of [&#x60;pending&#x60;, &#x60;partitioning&#x60;, &#x60;partitioned&#x60;, &#x60;refined&#x60;, &#x60;chunked&#x60;, &#x60;indexed&#x60;, &#x60;summary_indexed&#x60;, &#x60;keyword_indexed&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;]. The document is available for retrieval once it is in ready state. The summary index step can take a few seconds. You can optionally use the document for retrieval once it is in &#x60;indexed&#x60; state. However the summary will only be available once the state has changed to &#x60;summary_indexed&#x60; or &#x60;ready&#x60;. PDF files over 2000 pages are not supported in hi_res mode.
  # @param create_document_from_url_params 
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'create_document_from_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_document_raw
  # Create Document Raw
  # Ingest a document as raw text. On ingest, the document goes through a series of steps before it is ready for retrieval. Each step is reflected in the status of the document which can be one of [&#x60;pending&#x60;, &#x60;partitioning&#x60;, &#x60;partitioned&#x60;, &#x60;refined&#x60;, &#x60;chunked&#x60;, &#x60;indexed&#x60;, &#x60;summary_indexed&#x60;, &#x60;keyword_indexed&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;]. The document is available for retrieval once it is in ready state. The summary index step can take a few seconds. You can optionally use the document for retrieval once it is in &#x60;indexed&#x60; state. However the summary will only be available once the state has changed to &#x60;summary_indexed&#x60; or &#x60;ready&#x60;.
  # @param create_document_raw_params 
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'create_document_raw test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_document
  # Delete Document
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :async If true, performs document deletion asynchronously
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentDelete]
  describe 'delete_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document
  # Get Document
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentGet]
  describe 'get_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_chunk
  # Get Document Chunk
  # Gets a document chunk by its document and chunk ID.
  # @param document_id The id of the document.
  # @param chunk_id The ID of the chunk.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentChunkDetail]
  describe 'get_document_chunk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_chunk_content
  # Get Document Chunk Content
  # Returns the content of a document chunk in the requested format. Can be used to stream media of the content for audio/video documents.
  # @param document_id The id of the document.
  # @param chunk_id The ID of the chunk.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :media_type The desired media type of the content to return described as a mime type. An error will be returned if the requested media type is not supported for the chunk&#39;s document type.
  # @option opts [Boolean] :download Whether to return the content as a file download or a raw stream. If set to &#x60;true&#x60;, the content will be returned as a named file for download.
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @option opts [String] :range 
  # @return [Object]
  describe 'get_document_chunk_content test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_chunks
  # Get Document Chunks
  # List all document chunks sorted by index in ascending order. May be limited to a range of chunk indices with the &#x60;start_index&#x60; and &#x60;end_index&#x60; parameters. Documents created prior to 9/18/2024, which have not been updated since, have chunks which do not include an index and their index will be returned as -1. They will be sorted by their ID instead. Updating the document using the &#x60;Update Document File&#x60; or &#x60;Update Document Raw&#x60; endpoint will regenerate document chunks, including their index. Results are paginated with a max limit of 100. When more chunks are available, a &#x60;cursor&#x60; will be provided. Use the &#x60;cursor&#x60; parameter to retrieve the subsequent page.
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start_index The inclusive starting index of the chunk range to list. If omitted and &#x60;end_index&#x60; is present effectively limits results to at most one chunk matching &#x60;end_index&#x60;. If both &#x60;start_index&#x60; and &#x60;end_index&#x60; are omitted, results are not limited by index.
  # @option opts [Integer] :end_index The inclusive ending index of the chunk range to list. If omitted and &#x60;start_index&#x60; is present effectively limits results to at most one chunk matching &#x60;start_index&#x60;. If both &#x60;start_index&#x60; and &#x60;end_index&#x60; are omitted, results are not limited by index.
  # @option opts [String] :cursor An opaque cursor for pagination
  # @option opts [Integer] :page_size The number of items per page (must be greater than 0 and less than or equal to 100)
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentChunkList]
  describe 'get_document_chunks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_content
  # Get Document Content
  # Get the content of a document. The &#x60;media_type&#x60; parameter can be used to request the content in a different format. When requesting as &#x60;application/json&#x60; additional metadata about the document will be included. If the original document contained content such as images or other non-textual media, this response will include a text description of that media instead of the original file data. Using mime types such as &#x60;audio/mpeg&#x60; or &#x60;video/mp4&#x60; will stream the file in a format that can be provided to an audio video player.
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :media_type The desired media type of the content to return described as a mime type. An error will be returned if the requested media type is not supported for the document&#39;s type.
  # @option opts [Boolean] :download Whether to return the content as a file download or a raw stream. If set to &#x60;true&#x60;, the content will be returned as a named file for download.
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @option opts [String] :range 
  # @return [DocumentWithContent]
  describe 'get_document_content test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_source
  # Get Document Source
  # Get the source file of a document. The source file is the original file that was uploaded to create the document. If the document was created from a URL, the source file will be the content of the URL. If the document was created by a connection, the source file will vary based on the type of the connection. For example, a Google Drive connection will return the file that was synced from the Google Drive, while a SalesForce connection would return a JSON file of the data synced from SalesForce.
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [File]
  describe 'get_document_source test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document_summary
  # Get Document Summary
  # Get a LLM generated summary of the document. The summary is created when the document is first created or updated. Documents of types [&#39;xls&#39;, &#39;xlsx&#39;, &#39;csv&#39;, &#39;json&#39;] are not supported for summarization. Documents greater than 1M in token length are not supported. This feature is in beta and may change in the future.
  # @param document_id The id of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentSummary]
  describe 'get_document_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_documents
  # List Documents
  # List all documents sorted by created_at in descending order. Results are paginated with a max limit of 100. When more documents are available, a &#x60;cursor&#x60; will be provided. Use the &#x60;cursor&#x60; parameter to retrieve the subsequent page.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An opaque cursor for pagination
  # @option opts [Integer] :page_size The number of items per page (must be greater than 0 and less than or equal to 100)
  # @option opts [String] :filter The metadata search filter. Returns only items which match the filter. The following filter operators are supported: $eq - Equal to (number, string, boolean), $ne - Not equal to (number, string, boolean), $gt - Greater than (number), $gte - Greater than or equal to (number), $lt - Less than (number), $lte - Less than or equal to (number), $in - In array (string or number), $nin - Not in array (string or number). The operators can be combined with AND and OR. Read [Metadata &amp; Filters guide](https://docs.ragie.ai/docs/metadata-filters) for more details and examples.
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentList]
  describe 'list_documents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_document_metadata
  # Patch Document Metadata
  # @param document_id The id of the document.
  # @param patch_document_metadata_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [ResponsePatchdocumentmetadata]
  describe 'patch_document_metadata test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_document_file
  # Update Document File
  # @param document_id The id of the document.
  # @param file The binary file to upload, extract, and index for retrieval. The following file types are supported: Plain Text: &#x60;.eml&#x60; &#x60;.html&#x60; &#x60;.json&#x60; &#x60;.md&#x60; &#x60;.msg&#x60; &#x60;.rst&#x60; &#x60;.rtf&#x60; &#x60;.txt&#x60; &#x60;.xml&#x60; Images: &#x60;.png&#x60; &#x60;.webp&#x60; &#x60;.jpg&#x60; &#x60;.jpeg&#x60; &#x60;.tiff&#x60; &#x60;.bmp&#x60; &#x60;.heic&#x60; Documents: &#x60;.csv&#x60; &#x60;.doc&#x60; &#x60;.docx&#x60; &#x60;.epub&#x60; &#x60;.epub+zip&#x60; &#x60;.odt&#x60; &#x60;.pdf&#x60; &#x60;.ppt&#x60; &#x60;.pptx&#x60; &#x60;.tsv&#x60; &#x60;.xlsx&#x60; &#x60;.xls&#x60;. PDF files over 2000 pages are not supported in hi_res mode.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @option opts [Mode2] :mode 
  # @return [DocumentFileUpdate]
  describe 'update_document_file test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_document_from_url
  # Update Document Url
  # Updates a document from a publicly accessible URL. On ingest, the document goes through a series of steps before it is ready for retrieval. Each step is reflected in the status of the document which can be one of [&#x60;pending&#x60;, &#x60;partitioning&#x60;, &#x60;partitioned&#x60;, &#x60;refined&#x60;, &#x60;chunked&#x60;, &#x60;indexed&#x60;, &#x60;summary_indexed&#x60;, &#x60;keyword_indexed&#x60;, &#x60;ready&#x60;, &#x60;failed&#x60;]. The document is available for retrieval once it is in ready state. The summary index step can take a few seconds. You can optionally use the document for retrieval once it is in &#x60;indexed&#x60; state. However the summary will only be available once the state has changed to &#x60;summary_indexed&#x60; or &#x60;ready&#x60;. PDF files over 2000 pages are not supported in hi_res mode.
  # @param document_id The id of the document.
  # @param update_document_from_url_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentUrlUpdate]
  describe 'update_document_from_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_document_raw
  # Update Document Raw
  # @param document_id The id of the document.
  # @param update_document_raw_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [DocumentRawUpdate]
  describe 'update_document_raw test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
