=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for RagieRubySdk::ElementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ElementsApi' do
  before do
    # run before each test
    @api_instance = RagieRubySdk::ElementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElementsApi' do
    it 'should create an instance of ElementsApi' do
      expect(@api_instance).to be_instance_of(RagieRubySdk::ElementsApi)
    end
  end

  # unit tests for get_element
  # Get Element For Document
  # Returns an element for a specific id
  # @param element_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiDocumentElement]
  describe 'get_element test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_elements
  # List Elements For Document
  # List the latest elements for a document. The results are sorted by index in ascending order. Results are paginated with a max limit of 100. When more elements are available, a &#x60;cursor&#x60; will be provided. Use the &#x60;cursor&#x60; parameter to retrieve the subsequent page
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An opaque cursor for pagination
  # @option opts [Integer] :page_size The number of items per page (must be greater than 0 and less than or equal to 100)
  # @option opts [Array<DocumentElementType>] :type 
  # @option opts [Integer] :index_start 
  # @option opts [Integer] :index_end 
  # @option opts [String] :partition An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
  # @return [ListDocumentElements]
  describe 'list_elements test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
