=begin
#Ragie API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for RagieRubySdk::RetrievalsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RetrievalsApi' do
  before do
    # run before each test
    @api_instance = RagieRubySdk::RetrievalsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RetrievalsApi' do
    it 'should create an instance of RetrievalsApi' do
      expect(@api_instance).to be_instance_of(RagieRubySdk::RetrievalsApi)
    end
  end

  # unit tests for retrieve
  # Retrieve
  # @param retrieve_params 
  # @param [Hash] opts the optional parameters
  # @return [Retrieval]
  describe 'retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
